[project]
channels = ["conda-forge"]
name = "pomdp-env"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.3,<3"
gymnasium = ">=1.2.0,<2"
typing = ">=3.10.0.0,<4"
pyyaml = ">=6.0,<7"
matplotlib = ">=3.7.0,<4"
pillow = ">=10.0.0,<11"
jax = ">=0.4.0,<1"
jaxlib = ">=0.4.0,<1"
plotly = ">=5.0.0,<6"
imageio = ">=2.0.0,<3"
imageio-ffmpeg = ">=0.6.0,<0.7"

[pypi-dependencies]
kaleido = "==0.2.1"
