# Default configuration for grid environment

# Grid configuration
grid:
  n_x: 5
  n_y: 5
  n_z: 3
  d_max: 1

# Environment configuration
environment:
  max_steps: 100
  seed: 42

# Field configuration
field:
  type: "simple"
  seed: 42

# Actor configuration
actor:
  type: "grid"
  initial_position: [3, 3, 2]  # [i, j, k]
  noise_prob: 0.1
  seed: 42

# Reward configuration
reward:
  type: "distance_to_target"
  target_position: [3, 3, 2]  # [i, j, k]
  step_penalty: 0.1
  goal_reward: 10.0

# Rendering configuration
rendering:
  mode: "simple"  # "simple" or "advanced"
  show_wind: true
  show_target: true